### ISSUE TITLE
Use html5lib by default

### ISSUE THREAD

**Issue by kartikprabhu** [kartikprabhu/mf2py#59]
Currently mf2py defers to BeautifulSoup to choose the correct HTML parser. BS chooses in order lxml > html5lib > html.parser (see: https://www.crummy.com/software/BeautifulSoup/bs4/doc/#specifying-the-parser-to-use ) .

For malformed HTML these give different results ( see https://github.com/kartikprabhu/mf2py/issues/58#issuecomment-366536321 ). But html5lib is the closest to browser behaviour. 

So we should use html5lib by default unless over-ridden by user; if html5lib is not installed then differ to BS defaults.

related  #41

Discuss! vote.

cc @kevinmarks @sknebel @bear @tommorris @snarfed

**Comment by kevinmarks** [comment]
+1 on using html5lib by default.
The html.parser does very odd things.

**Comment by kartikprabhu** [comment]
also cc @tantek for outside viewpoint

**Comment by snarfed** [comment]
fwiw bridgy has [overridden mf2py for years](https://github.com/snarfed/bridgy/blob/master/util.py#L632) to use lxml since it's [significantly faster](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#differences-between-parsers) (actually more like less slow: https://github.com/snarfed/bridgy/issues/578#issuecomment-189296654 ), and at scale i care about that more than minor edge case and compatibility differences.

**Comment by kartikprabhu** [comment]
@snarfed so making html5lib default will not affect the Brigdy performance since it is overridden anyway?

aside: Still curious if the implied-name-fix solves your instagram woes.

**Comment by kevinmarks** [comment]
I remember adding lxml to speed up html5lib, and doing a bit of profiling
before, but would the bridgy archive be a good corpus to profile against to
see if there are bottlenecks?

**Comment by kartikprabhu** [comment]
fixed by ^ but keeping open
